image:
  file: .gitpod.Dockerfile

tasks:
  - name: docker_up
    command: sudo docker-up
  - name: display_sudo_permissions
    openMode: split-right
    command: docker run -it --rm drud/ddev-webserver:v1.16.3 ls -l /usr/bin/sudo